#import "@preview/charged-ieee:0.1.4": ieee

// Acronyms
#import "@preview/acrostiche:0.5.1": *

#init-acronyms((
  "STAC": "Spacecraft Tracking & Command Station",
  "VHF": "Very High Frequency",
  "UHF": "Ultra High Frequency",
  "FE": "Front End",
  "LVDS": "Low Voltage Differential Signalling",
  "DVB-S2": "Digital Video Broadcasting - Satellite - Second Generation",
  "ACM": "Adaptive Coding and Modulation",
  "TS": "Transport Stream",
  "XTCE": "XML Telemetric and Command Exchange",
  "SDR": "Software Defined Radio",
  "UPL": "User Packet Length",
  "DFL": "Data Field Length",
  "BBFRAME": "Baseband Frame",
  "IQ": "In-phase and Quadrature",
  "SPI": "Serial Peripheral Interface",
  "PBR": "Passive Bistatic Radar",
  "ISS": "International Space Station",
  "COTS": "Commercial Off-The-Shelf",
  "BCH": "Bose-Chaudhuri-Hocquenghem",
  "LDPC": "Low-Density Parity-Check",
  "FECFRAME": "Forward Error Correction Frame",
  "PLFRAME": "Physical Layer Frame",
  "FEC": "Forward Error Correction",
  "SNR": "Signal to Noise Ratio",
  "CNR": "Carrier to Noise Ratio",
  "ITU": "International Telecommunication Union",
  "PS": "Processing System",
  "PL": "Programmable Logic",
  "CCSDS": "Consultative Committee for Space Data Systems",
  "ESA": "European Space Agency",
  "FYS": "Fly Your Satellite",
  "RF": "Radio Frequency",
  "CCDD": "Core Flight System (CFS) Command and Data Dictionary",
  "IPC": "Inter-Process Communication",
  "ISM": "Industrial, Scientific, and Medical",
  "SoC": "System on Chip",
  "CRC-8": "8 bit Cyclic Redundancy Check",
  "GSE": "Generic Stream Encapsulation",
  "FIFO": "First In First Out",
  "I2C": "Inter-Integrated Circuit",
  "CAN": "Controller Area Network",
  "IP": "Internet Protocol",
  "PDR": "Preliminary Design Review",
  "BER": "Bit Error Rate",
  "FPGA": "Field Programmable Gate Array",
  "ADC": "Analog to Digital Converter",
  "DAC": "Digital to Analog Converter",
  "ETSI": "European Telecommunications Standards Institute",
  "VCM": "Variable Coding and Modulation",
  "VL-SNR": "Very Low Signal-to-Noise Ratio",
  "BPSK": "Binary Phase Shift Keying",
  "PDU": "Protocol Data Unit",
  "AWGN": "Additive White Gaussian Noise",
  "RTL": "Register Transfer Level",
  "TT&C": "Telemetry, Tracking and Command",
  "CCM": "Constant Coding and Modulation",
  "EDHPC": "European Data Handling & Data Processing Conference",
  "TBC": "To Be Confirmed",
  "OBC": "On Board Computer",
  "EIRP": "Effective Isotropic Radiated Power",
  "RAM": "Random Access Memory",
  "FMC": "FPGA Mezzanine Card",
  "BBHEADER": "Base Band Header",
  "APSK": "Amplitude and Phase Shift Keying",
  "MATYPE": "Mode Adaption Type",
  "MODCOD": "MODulation and CODing rate",
  "TLE": "Two-Line Element set",
  "UART": "Universal Asynchronous Receiver-Transmitter",
  "MSB": "Most Significant Bit",
  "LSB": "Least Significant Bit",
  "FSPL": "Free Space Path Loss",
  "LUT": "Look Up Table",
  "VSWR": "Voltage Standing Wave Ratio",
))

#show: ieee.with(
  title: [Speech],
  abstract: [
    
  ],
  authors: (
    (
      name: "Daniel Stebbings",
      department: [Department of Electronic and Electrical Engineering],
      organization: [University of Strathclyde],
      location: [Glasgow, Scotland, UK],
      //email: "Email: danielastebbingsdaniel@gmail.com",
    ),

  ),
  index-terms: ("AI", "Speech Recognition"),
  bibliography: bibliography((

  )),
  figure-supplement: [Fig.],
)

= Introduction <sec:Introduction>
dwdw